static_key:
- 3009b87324da39e76f60a85fe030b2f8
- 9cd7dd0873172eda537bafe618ec72b4

entry:
- path: /test1
  cmd: ["./extras/cgify.sh", "./test-script.sh", "a", "b"]
- path: /test2
  cmd: ["./extras/cgify.sh", "./test-script.sh", "1", "2"]
- path: /test3
  cmd: ["./extras/test-script.sh", "1", "2"]
  allow_parallel: true
  allow_sub_path: true
  hijack_tcp: true
